/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package demohilos;

/**
 *
 * @author iserm
 */
public class DemoHilos1 extends javax.swing.JFrame {

    /**
     * Creates new form DemoHilos1
     */
    public DemoHilos1() {
        initComponents();
        new IncrementaValorHilo().start();
        new DecrementaValorHilo().start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblIncrementa = new javax.swing.JLabel();
        lblDecrementa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Demo contador con hilos");

        lblIncrementa.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblIncrementa.setForeground(new java.awt.Color(0, 51, 255));
        lblIncrementa.setText("Up");

        lblDecrementa.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblDecrementa.setForeground(new java.awt.Color(255, 0, 0));
        lblDecrementa.setText("Down");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblIncrementa)
                        .addGap(146, 146, 146)
                        .addComponent(lblDecrementa))
                    .addComponent(jLabel1))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIncrementa)
                    .addComponent(lblDecrementa))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    /* Clase Hilo 1 */
    class IncrementaValorHilo extends Thread {
        public void run() {
            int contador = 0;
            while(true) {
                try {
                    sleep(50);
                } catch (InterruptedException e) {
                    
                }
                if (contador == 1000)
                    contador = 0;
                lblIncrementa.setText(Integer.toString(contador++));
            }
        }
    }
    
    class DecrementaValorHilo extends Thread {
        public void run() {
            int contador = 1000;
            while(true) {
                try {
                    sleep(50);
                } catch(InterruptedException e) {
                    
                }
                if(contador == 0)
                    contador = 1000;
                lblDecrementa.setText(Integer.toString(contador--));
            }
        }
    }
    
    
    /* Clase Hilo 2 */
    
    
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DemoHilos1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DemoHilos1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DemoHilos1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DemoHilos1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DemoHilos1().setVisible(true);
                                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblDecrementa;
    private javax.swing.JLabel lblIncrementa;
    // End of variables declaration//GEN-END:variables
}
